### ISSUE TITLE
Disable or remove a stick assignment?

### ISSUE THREAD

**Issue by harf4ng** [SCToolsfactory/SCJMapper-V2#75] opened 2018-07-06 21:55 UTC
Hi,
Unsure this is normal or not, but I have noticed that if we deactivate (or disable) a stick assignment, then if we go in the star citizen UI, the assignment is gone, that is normal.
But if we "remove" a stick assignment, then the assignment is not gone in star citizen UI, but instead it shows something like (input1122545).
This also means that if we ask SCJ Mapper to start from a brand new config (not default, but empty), then in the star citizen UI we have a lot of those strange lines, instead of blank lines.
Is it a wanted behaviour?
Thanks

**Comment by bm98** [comment] 2018-07-06 22:46
Disable is as you write, however removing should leave the assignments of CIG for that command but no other ones? - can you sent me an example XML where this happens and may be a screenshot of the game GUI - not seen this before.
Also the one where you start empty - well how empty is the XML then?
Usually you would assign one or two devices with jsN - but also here you may send (attach) such an example as I never saw this (so far...)

**Comment by harf4ng** [comment] 2018-07-07 09:43
Look. Init empty shows that in your software:
![image](https://user-images.githubusercontent.com/22551859/42409427-a16d3bce-81da-11e8-8fb6-4018fdc807e6.png)

And once in the game if I apply the config, it displays that:
![image](https://user-images.githubusercontent.com/22551859/42409455-f8d4c1f2-81da-11e8-9db5-73634a1a1f08.png)

You see the issue? Unsure why it does that.

Thanks

**Comment by harf4ng** [comment] 2018-07-07 09:49
This is the problem with the default empty xml.
Though indeed if I remove a line it brings back the default star citizen one.

btw the latest version is 3.2 compatible? Or could there be some issues for now?

Thanks

**Comment by bm98** [comment] 2018-07-15 18:47
Could be that you need to ReAssign the devices you don't use to n.a.  and only the used ones to js1.. 4.
In any case you need the game to find the used ones at the very beginning or re-map them in order to have it working properly.
CIG recognizes I think 4 Joysticks only - an empty file would then only list the devices used in SC and not all 9 in the XML (don't know if this is the cause...)
For disabling - there is a way to do it rather fast - see the Guide page 19.
And yes it should (does here) work with 3.2.x

**Closed** 2018-08-04 11:47 UTC
